### ISSUE TITLE
[ERROR] Failed to encrypt JavaScript files

### ISSUE THREAD

**Issue by abada** [FokkeZB/tn#47]
When run 

`tn --android --device --device-id LC5AZZ703556` in android   device
```
[ERROR] Failed to encrypt JavaScript files
[ERROR] This application cannot be built with the Titanium open source SDK because it is an Appcelerator Platform registered application. Please use the Appcelerator Platform CLI tools or Appcelerator Studio to build this application.
```

**Comment by FokkeZB** [comment]
So it seems that `tn` decides to use `ti build` instead of `appc run`. That is probably because [this code](https://github.com/FokkeZB/tn/blob/9436509e69b0445c942ac4e8ea84b224700a5918/bin/cli.js#L127) didn't find an `appc-app-id` element in `tiapp.xml` but the `guid` is known as a platform guid. So you should replace the `guid`.

**Comment by abada** [comment]
Thank you @FokkeZB it works now , i just added these tags 

```
<guid> </guid>
  <property name="appc-app-id" type="string"> </property>
  <property name="appc-org-id" type="string"> </property>
  <property name="appc-creator-user-id" type="string"> </property>
```
